[tool.poetry]
name = "py-package-template"
version = "0.1.0"
description = "Modern Python package template"
authors = ["Giacomo Pojani <giacomo.pj@hotmail.it>"]
packages = [
    {include = "src"}
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-cov = "^3.0.0"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
